on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        id: 'zap-scan'
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://gstorebhutan.company.site'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: "false"
          fail_action: "false"
          report_file: 'zap_scan_report_${{ github.sha }}.html'

      - name: Check for High, Medium, Low Alerts
        id: check-alerts
        run: |
          # Extract the relevant data from the ZAP report
          grep -iE 'High|Medium|Low' zap_scan_report_${{ github.sha }}.html > alerts.txt || true
          if [ -s alerts.txt ]; then
            echo "RISK_LEVELS_PRESENT=true" >> $GITHUB_ENV
          else
            echo "RISK_LEVELS_PRESENT=false" >> $GITHUB_ENV
          fi
          
      - name: Send ZAP Scan Results
        if: env.RISK_LEVELS_PRESENT == 'true'
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          text-message: |
            ZAP Scan Report detected High, Medium, or Low risk levels.
            [View Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          google-chat-webhook: ${{ secrets.CHAT_WEBHOOK }}
