name: ZAP Scan

on:
  workflow_dispatch:

jobs:
  build:
    name: PEN test
    runs-on: ubuntu-latest
    steps:
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.12.0
          with:
            target: 'https://btngaming.com'